### PR TITLE
Remove shorthand-property-no-redundant-values

### PR DESCRIPTION
**Pull request by edg2s**
Was added in #5 without discussion.

### CODE REVIEW

**Comment by Volker-E** [comment]
I understand the request for discussion, nonetheless I'm convinced we should stick to it. 
Shorthand notation is a syntax feature following DRY principle.
Most devs have probably come across of the `margin: 1em 2em` shorthand notation for `top/bottom left/right` value assignment, the three values notation `margin: 1em 2em 2em` for `top left/right bottom` is a little more rare. 
I see a disadvantage of mixing the notations across our code base when there is support to do it  one specific way.

**Comment by edg2s** [comment]
The three value notation is really weird and the fourth value is not intuitive. It is mostly not used at the moment so enforcing it will result in lots of changes that will reduce readability.

**Comment by jdforrester** [comment]
This is really quite messy when run on current code bases. I'm not sure it's not a good idea, but for now let's kill it and bring it back later?

**Comment by Volker-E** [comment]
In the whole OOjs UI codebase there are two (! with Apex & MediaWiki for the same property three) instances where the three value notation would come in:

> src/styles/layouts/FieldsetLayout.less
>  8:2  ✖  Unexpected longhand value '0.01px 0 0 0' instead of '0.01px 0 0'   shorthand-property-no-redundant-values

And that is the error message. Pretty clear, especially when such error also comes up:
> src/themes/apex/tools.less
>  412:3  ✖  Unexpected longhand value '0.3125em 0 0.3125em 0' instead of '0.3125em 0'   shorthand-property-no-redundant-values

How many rules are we enforcing in eslint, that are not well known to some devs?

**Pull request merged**
