### PR TITLE
build: Drop Node.js version 12.x and update to '14.x, 16.x'

### PR DESCRIPTION
**Pull request by Volker-E**

### CODE REVIEW

**Comment by Volker-E** [comment]
(a) I was just checking MediaWiki core CI, which uses a 14.x node. If we still use node 12, let's stall this.

**Comment by Volker-E** [comment]
Revisiting this, I assume, you would rather stay aligned to Stylelint upstream…? @jdforrester

**Comment by edg2s** [comment]
Is the migration from 12.x complete @jdforrester ?

**Comment by jdforrester** [comment]
> Is the migration from 12.x complete @jdforrester ?

Yes, except for services which are out of scope for this. Let's ship it.

**Review by jdforrester — APPROVED** [review]

**Pull request merged**
