### PR TITLE
build: Rename 'grade-a' and 'grade-c' to 'support-modern' and 'suppor…

### PR DESCRIPTION
**Pull request by Volker-E**
…t-basic'

Use more self-explaining language for those rules.

### CODE REVIEW

**Review by Krinkle — APPROVED** [review]

**Comment by jdforrester** [comment]
Are we going to update all the documentation about RL, then?

**Comment by jdforrester** [comment]
Also this is a breaking change, which we don't generally do if we can avoid it.

**Comment by Volker-E** [comment]
Given [this has been introduced in v0.10.2](https://github.com/wikimedia/stylelint-config-wikimedia/commit/4ce0f90e1cf499f520956d07545b96e11dce3583) and is MediaWiki specific expert terminology I don't expect a lot of breakages:
https://codesearch.wmcloud.org/search/?q=grade-a&i=nope&files=&excludeFiles=&repos=

And we're not using “grade” in a lot of places or exclusively. Patch for changing support browser terminology is up at https://gerrit.wikimedia.org/r/c/mediawiki/core/+/68479

**Comment by Krinkle** [comment]
Any references to this can be updated downstream in the same patch as when they update to >= 0.11.x.

I'm still +1 on this, but agree that this may need to wait if we don't yet want to go from 0.10.x to 0.11.0.

**Comment by jdforrester** [comment]
Eh, it's fine. :-) I just wanted to make sure we were consistent.

**Pull request merged**
