### PR TITLE
Rules addition #3

### PR DESCRIPTION
**Pull request by Volker-E**
Adding rest of stylelint rules

Issue: #3

### CODE REVIEW

**Comment by jdforrester** [comment]
Needs rebase.

**Comment by edg2s** [comment]
Not sure I'm a fan of 'shorthand-property-no-redundant-values'

While it is clear to most that `padding: A B` maps to `padding: A B A B`, I don't think it is obvious that `padding: A B C` maps to `padding: A B C B`, as opposed to `A B C C` or `A B C 0`

**Comment by edg2s** [comment]
`function-url-scheme-whitelist` gives errors for images embedded as data URIs. Those should be allowed.

**Comment by edg2s** [comment]
We should also discuss the `selector-attribute-brackets-space-inside`. In JS we now have spaces inside all types of square brackets.

**Comment by edg2s** [comment]
I also get the following warning for an IE gradient rule:

`Expected "DXImageTransform.Microsoft.gradient" to be "dximagetransform.microsoft.gradient"   function-name-case`

**Comment by ntwb** [comment]
> I also get the following warning for an IE gradient rule:
> 
> `Expected "DXImageTransform.Microsoft.gradient" to be "dximagetransform.microsoft.gradient" function-name-case`

I also hit upon this issue a week or so back, I'm wondering if stylelint should make exceptions for IE gradients case in the rule `function-name-case`? (There are existing exceptions like `ButtonText` in the `value-keyword-case`)

I'm not very familiar with MS's specs on these, nor did I find a reference to if case is sensitive or not from a quick search...

**Comment by Volker-E** [comment]
@ntwb You're right, it's not outspoken in the [MSDN specs](https://blogs.msdn.microsoft.com/ie/2008/09/08/microsoft-css-vendor-extensions/ ) ([another example](https://msdn.microsoft.com/en-us/library/ms532972(v=vs.85).aspx)). 
But given that lower-casing would lower the readability of those anyways already hard to read proprietary extension, it shouldn't be enforced. I'm preparing a follow-up patch.

**Pull request merged**
