### PR TITLE
v0.4.2 accept stylelint 7.8.0 or above

### PR DESCRIPTION
**Pull request by juliengirault**

### CODE REVIEW

**Comment by Volker-E** [comment]
From IRC conversation before 82dc18e96e46a0b293ab1748e7a9f01bbd5c66ef:

> <Volker_E> James_F: no `~` any more?
> <Volker_E> James_F: as in no minor version compat?
> <James_F> Volker_E: Nope, pinning means we don't get screwed over when upstream adds new rules.

**Comment by Volker-E** [comment]
I'm still unsure, if [allowing patch versions](https://docs.npmjs.com/misc/semver) as in `~7.8.0` isn't a wishful thing? @edg2s

**Comment by ntwb** [comment]
See also https://github.com/stylelint/stylelint/tree/v8#semantic-versioning-policy

As of v8 stylelint are changing, for the better IMHO their semantic versioning policy, it basically aligns itself with the ESLint semver policy and the recommendation will be to use `~` rather than `^` going forward.

**Comment by jdforrester** [comment]
We repeatedly get everything in Wikimedia CI broken by trusting upstreams (eslint and stylelint and several others) both to make no intentional breaking changes without major version bumps (SemVer) and also to avoid making any accidental breaking changes. Our trust keeps being proven misplaced, sadly. Consequently we pin everything; the manual updates I have to make every few months are trivial compared to the much more stressful running around trying to fix things after the fact (which often seem to happen during deploy windows, for added fun).

**Comment by ntwb** [comment]
@jdforrester You should switch all of Wikimedia's uses of both eslint and stylelint from `^` to `~`, both packages recommend this as I noted above, as to eslint and stylelint breaking _trust_ I'm not so sure of, if you don't follow there semver policy then 😏

**Pull request closed without merging**
